### ISSUE TITLE
没有找到论文《Polynomial Algorithms for Byzantine Agreement》

### ISSUE THREAD

**Issue by YoungWilliamZ** [yeasy/blockchain_guide#100]
在 [拜占庭问题与算法](https://yeasy.gitbooks.io/blockchain_guide/content/distribute_system/bft.html)中，您提及到：
> 拜占庭容错算法最早的讨论在 1980 年 Leslie Lamport 等人发表的论文《Polynomial Algorithms for Byzantine Agreement》，之后出现了大量的改进工作。

但在google scholar[搜索](https://scholar.google.com/scholar?q=Polynomial+Algorithms+for+Byzantine+Agreement&hl=en&as_sdt=0&as_vis=1&oi=scholart)与 L. Lamport 老爷子的[主页](http://lamport.azurewebsites.net/pubs/pubs.html)中并没有找到匹配论文。

希望作者能够核实。

再次感谢作者能够写出这么好的书~

**Comment by yeasy** [comment]
Fixed, thanks!
