### ISSUE TITLE
Fabric在实际场景下部署在哪里？

### ISSUE THREAD

**Issue by guanpengchn** [yeasy/blockchain_guide#109]
您好，这个问题困扰我很久，因为像公有链，每个电脑都是一个节点，能够拿到全部账本。

而Fabric又应该怎么部署呢，如果三家企业想做一份儿账本，那么应该由谁来出服务器？其中的peer节点应该部署在哪家企业里？如果每家企业都要部署peer节点，那么endorsing peer和commit peer又应该怎样分配，orderer节点又放在哪里呢？

如果都放在一个地方岂不是中心化的了

**Comment by LeoMoonStar** [comment]
可以都部署在云上 选择同一家或者不同的云服务商
每一个org一个服务器

**Comment by guanpengchn** [comment]
@LeoMoonStar 感谢回答，那还有一个问题，就是每家部署几个peer节点呢，endorsing peer和commit peer又应该怎样分配，orderer节点又放在哪里呢？

**Comment by LeoMoonStar** [comment]
看需求，一般一个orderer 两个peer，org size大的话再说，一个endorsing，其他都是commit，orderer 和同org的其他peer放一起

**Comment by guanpengchn** [comment]
那么在共识的第一阶段，也就是执行chaincode并且返回给application那里，一定需要验证所有的endorsing peer节点给出的结果相同才可以么？是否存在大多数验证通过即可的这种情况，可以在chaincode或Application中去写么？如果有这种情况的话那么endorsing peer节点是不是应该存在比例的问题，比如说A,B,C三个组织，如果B的权重大，则应该按照1：2：1的比例去部署？

**Comment by yeasy** [comment]
联盟链，一般会参考业务场景。
部署方式和比例可以联盟商讨一种方式，也可以大家遵循一定原则自行决定。

**Comment by guanpengchn** [comment]
@yeasy 感谢回答，那么就像我刚刚提到的需求，如果50%的节点通过即可的话，这样的逻辑应该是在Fabric的哪部分去写呢，有什么具体的API可以看么？

**Comment by yeasy** [comment]
项目推荐的书可以读一下。
