### ISSUE TITLE
questions on proto

### ISSUE THREAD

**Issue by dexhunter** [yeasy/blockchain_guide#111]
At [repo hyperledger/fabric-protos](https://github.com/hyperledger/fabric-protos/blob/master/peer/transaction.proto#L42-L47), transactions are defined simply as:

```protobuf
message Transaction {

    // The payload is an array of TransactionAction. An array is necessary to
    // accommodate multiple actions per transaction
    repeated TransactionAction actions = 1;
}
```

while [at book] (https://github.com/yeasy/blockchain_guide/blob/master/fabric_design/design.md), transactions are much more complex:

```protobuf
message Transaction {
    enum Type {
        UNDEFINED = 0;
        // deploy a chaincode to the network and call `Init` function
        CHAINCODE_DEPLOY = 1;
        // call a chaincode `Invoke` function as a transaction
        CHAINCODE_INVOKE = 2;
        // call a chaincode `query` function
        CHAINCODE_QUERY = 3;
        // terminate a chaincode; not implemented yet
        CHAINCODE_TERMINATE = 4;
    }
    Type type = 1;
    //store ChaincodeID as bytes so its encrypted value can be stored
    bytes chaincodeID = 2;
    bytes payload = 3;
    bytes metadata = 4;
    string uuid = 5;
    google.protobuf.Timestamp timestamp = 6;

    ConfidentialityLevel confidentialityLevel = 7;
    string confidentialityProtocolVersion = 8;
    bytes nonce = 9;

    bytes toValidators = 10;
    bytes cert = 11;
    bytes signature = 12;
}
```

Just wonder if it is caused by version update or is the book trying to give the whole picture on this? 

Besides, later in the section, it says World State is stored as a merkely tree but I could not find the source on fabric documentation, could you point me to the source of the writing?

Thank you very much!

**Comment by yeasy** [comment]
Believe because of different versions.
Well, currently, it's a one-level merkle trie.
