### ISSUE TITLE
章节缺失

### ISSUE THREAD

**Issue by YYYMagic** [yeasy/blockchain_guide#129]
大神你好，
阅读中发现区块链应用开发的“简介”页和“链上代码工作原理”页是空白，这个会考虑填上吗

**Comment by SirKong** [comment]
谢谢您的邮件，我已收到，我会尽快给您回复。

**Comment by shingsheep** [comment]
您好：    您的来信已收悉，我会尽快回复。谢谢。

**Comment by yeasy** [comment]
No plan yet. Do you think it is the most important one to read?

**Comment by YYYMagic** [comment]
> No plan yet. Do you think it is the most important one to read?

Thanks for replying. 
It may be better to see the guide is fully completed, but the blank page does not block reading. Thanks again for your great work in this guide!

**Comment by yeasy** [comment]
You may check the latest version at https://github.com/yeasy/blockchain_guide/blob/master/SUMMARY.md.
