### ISSUE TITLE
peer channel create error

### ISSUE THREAD

**Issue by NaNYeYuan** [yeasy/blockchain_guide#130]
Error: got unexpected status: BAD_REQUEST -- error validating channel creation transaction for new channel 'businesschannel', could not successfully apply update to template configuration: error authorizing update: error validating DeltaSet: policy for [Group] /Channel/Application not satisfied: implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Admins' sub-policies to be satisfied.

**Comment by yeasy** [comment]
Which code are you using?

**Comment by NaNYeYuan** [comment]
Thanks for your reply. I am reading Chapter 9: "Fabric安装与部署" (Second Edition)。Following those procedures, I have started 3 peers (v2.4) via different ports.  When using code in section 9.4.5 "创建通道", error above shows. Codes are as below. 
APP_CHANNEL=businesschannel
TIMEOUT=30
CORE_PEER_LOCALMSPID="Org1MSP" \
CORE_PEER_MSPCONFIGPATH=/etc/.../Admin@org1.example.com/msp \
peer channel create \ 
-o orderer0.example.com: 7050 \
-c: ${APP_CHANNEL} \
-f ./$APP_CHANNEL.tx \
--timeout "${TIMEOUT}s" \
--tls \
--cafile /etc/.../tlscacerts/tlsca.example.com-cert.pem

**Comment by yeasy** [comment]
Try this one?
https://github.com/yeasy/docker-compose-files/tree/master/hyperledger_fabric
