### ISSUE TITLE
PDF Viewing Bug

### ISSUE THREAD

**Issue by YouYue123** [yeasy/blockchain_guide#27]
Hi Yeasy,

I read your pdf blockchain_guide today. And it's amazing. Thanks for sharing your knowledge about blockchain and this cookbook is quite helpful to construct a overall sight in blockchain.

But there is a problem related to the PDF version. Some of the formula can not present correctly.

For example, in page 57. 

多于**Fomula**的叛变者时有没有可能有解决方案

I have tried build-in PDF reader in Mac Chrome Version 54.0.2840.98 (64-bit)  and Mac Adobe Acrobat Reader Version 2015.009.20069.

Hope it can help you.

Thanks

**Comment by yeasy** [comment]
Thanks for the reporting, seems something is wrong with the gitbook rendering.
Would like to suggest you use the online version currently: https://yeasy.gitbooks.io/blockchain_guide/content/consensus/bft.html.
Thanks!

**Comment by YouYue123** [comment]
Thanks!!
