### ISSUE TITLE
hyperledger章节一个小细节不明白

### ISSUE THREAD

**Issue by dongpengfei** [yeasy/blockchain_guide#29]
这个地方的“钱继区块”是一个不明白的名词，还是拼写错误？

![fwnt380 bvemp91 i vn5](https://cloud.githubusercontent.com/assets/1546140/20923927/c29640f6-bbe9-11e6-85c1-b27abf65d0a3.png)

**Comment by yeasy** [comment]
sorry, it should be 前继~
