### ISSUE TITLE
Fabric1.0并发情况下报错的问题

### ISSUE THREAD

**Issue by bigstar119** [yeasy/blockchain_guide#52]
版主好，我使用Fabric1.0，并用官方提供的资产转移的示例，在并发测试时报异常，异常信息如下：
                        java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.hyperledger.fabric.sdk.exception.TransactionEventException: 
                       Received invalid transaction event. Transaction ID 908eb057a2ccaefacf39ee95ba4c9c15e4a4173ca0877bd4f3d32ac8b71e6f09 status 11 
                        状态码:11，的定义如下：
                        
![image](https://user-images.githubusercontent.com/24514189/28761651-c3b6ea04-75e2-11e7-9e46-0d44bfc4c70f.png)

感觉是并发读冲突了。。这个问题您之前在做性能测试时有遇到过吗？如何解决的？

**Comment by liutc** [comment]
上周我在项目里面遇到过一次类似的报错。后来分析了一下，确实里面存在事物冲突。
个人观点：这种情况下，冲突就是冲突了，不用解。需要在应用端处理为对应操作失败。

**Comment by bigstar119** [comment]
哦，不过在应用端控制可能也比较麻烦，要考虑多机分布式部署的情况，可能还得处理分布式锁。。以太坊就没有这个充突的问题，看来设计理念不同。

**Comment by liutc** [comment]
fabric在这块儿我把它当成是乐观锁看。分布式系统读写冲突是必然存在的，根据业务逻辑判断用乐观还是悲观策略。如果乐观策略，应用端不需要加额外的锁；只是处理返回的时候注意有可能事务提交因为冲突而失败。

**Comment by bigstar119** [comment]
哦，那就是在应用程序端，判断特定的异常类型来处理。。另外，fabric1.0的性能您做过测试了吗？TPS大大概是多少？我在本机测试的结果只有20左右，1000并发下后台还有异常？按理说1.0版本不应该是这样的性能表现。。使用Fabric1.0时，如果是高性能要求的场景，需要额外配置哪些东西吗？

**Comment by spyhole** [comment]
@yeasy

**Comment by yeasy** [comment]
@liutc is correct, it's MVCC mechanism, hence potentially some conflict may happen.

No worry about the result, MVCC will help make sure no mistake.
