### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by pranavburnwal** [yeasy/blockchain_guide#53]
I have been following this repo for sometime now. 

I have to copy things to Google translate per page and then figure things out.
Will it be possible to put forth an English version {using auto translate itself}.
Will become much easier to read. If you know a way and I can help, do let me know.

Thanks!
P

**Comment by yeasy** [comment]
Sorry, we do not know if there's auto-translate method now.

If you wanna help start some English version, pls let me know, would like to help, certainly.

**Comment by pranavburnwal** [comment]
Sorry for the delay, yeah definitely porting to English will make a lot of sense and help a lot of people.
I will look towards how I can do that. If you have any suggestions please feel free to share.

**Comment by yeasy** [comment]
@pranavburnwal sure, feel free to let me know if you need help. I believe those tools like transifex or zanata might help to do the translation and review work.

**Comment by pranavburnwal** [comment]
Just one thing @yeasy. Which language is this currently? Text readers getting confused, got different output from different once.

**Comment by yeasy** [comment]
Existing language is Chinese.

I can create an `en` branch for u if needed.

**Comment by aabdulwahed** [comment]
Yes please If you can make an English version of it. this will be so great

**Comment by pranavburnwal** [comment]
@yeasy Please create a branch with 'en'. I couldn't find a one-click convert tool.
I will manually convert the pages.

**Comment by yeasy** [comment]
@pranavburnwal 
Here u are: https://github.com/yeasy/blockchain_guide/tree/i18n_en.
It's based on the master branch, and can keep sync, too.
Is this OK for a start?

**Comment by jayanthdeejay** [comment]
I used Google translate to translate the PDF and it seem to translate the entire document except I'm not sure how reliable the translation is considering I've used it in the past and a native Chinese speaker once told me that the translation that it provided is not accurate.

@yeasy could you please try and verify the accuracy of the Google translate.

![screen shot 2017-12-08 at 4 32 42 pm](https://user-images.githubusercontent.com/2188493/33786114-d641d60c-dc35-11e7-8d4e-48db8c2b42d7.png)


It would be easier for a Native Chinese speaker to validate it than anyone else. Or any other suggestions?

**Comment by yeasy** [comment]
@jayanthdeejay G's translation is good, especially for technical content.
Besides, would u like to learn some Chinese :-)
