### ISSUE TITLE
Fabric 1.0 client APP 疑問

### ISSUE THREAD

**Issue by Xeriou** [yeasy/blockchain_guide#54]
您好：
想請問你個基本的問題
目前我把自己的 fabric 環境建立好，chaincode 也已經部屬完畢
現在我需要部屬一個 client 端的 APP (Nodejs)
但我疑惑在這
因為官方提供的 Application 的範例中，有個 cred 資料夾
裡面放了 其中一個節點的私鑰跟公鑰，這看起來是為了這個範例所產生出來的
這個看起來似乎是必要的？
還是說 如果有架設好 fabric-ca 就不需要這個公私鑰?
(以上問題可能是我理解錯誤)

**Comment by yeasy** [comment]
Hi, would suggest u ask at https://chat.hyperledger.org/channel/fabric-sdk-node.
