### ISSUE TITLE
Run the network, register the program, Test the URL from SOAP UI - HTTP:\LOCALHOST:7050\

### ISSUE THREAD

**Issue by Senthilmca** [yeasy/blockchain_guide#58]
Hi All – 
We are trying to implement Blockchain program using one of the sample program (SimpleSample.JAVA) listed out in the below link. We are able to setup the environment to execute the program in Windows10 operating system. But, when we test it from SOAPUI with URL http:\\localhost:7050 with HTTP METHOD GET/POST, we get an error saying ‘- ERROR GETTING RESPONSE; ORG.APACHE.HTTP.NOHTTPRESPONSEEXCEPTION: THE TARGET SERVER FAILED TO RESPOND’.

Need your inputs on how this can be rectified to run the Blockchain program? The Blockchain program is successfully registered with the Docker. We got stuck post trying from the URL.

Linked followed for the implementation: https://www.ibm.com/developerworks/library/j-chaincode-for-java-developers/index.html

File – SIMPLESAMPLE.JAVA

With Regards,
Senthil R.

**Comment by yeasy** [comment]
pls ask in the java-sdk channel: https://chat.hyperledger.org/channel/fabric-sdk-java.
