### ISSUE TITLE
Register error

### ISSUE THREAD

**Issue by zjgsuwk** [yeasy/blockchain_guide#6]
您好！我参照您书中的"权限管理"的样例，注册用户时出现如下错误：

 curl -i -H "Accept:application/json" -H "Content-Type:application/json" -X POST -d "{\"enrollId\":\"wukai\",\"enrollSecret\":\"123456\"}" 127.0.0.1:5000/registrar
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Headers: accept, content-type
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Wed, 13 Jul 2016 01:08:05 GMT
Content-Length: 91

{"Error": "rpc error: code = 2 desc = 'Identity lookup error: sql: no rows in result set'"}root@vp2:/#

能帮忙解决吗，谢谢！

**Comment by yeasy** [comment]
hi, `wukai` is not a permitted member, you may need to first add the key in `$GOPATH/src/github.com/hyperledger/fabric/membersrvc/membersrvc.yaml`.
Thanks!

**Comment by yeasy** [comment]
Will close first, please reopen if still meet issues.
Thanks!
