### ISSUE TITLE
比特币的原理与设计那一章存在笔误

### ISSUE THREAD

**Issue by Hcancan** [yeasy/blockchain_guide#60]
![image](https://user-images.githubusercontent.com/19147113/32045577-2d8be11c-ba73-11e7-9598-cb5404f0b5a6.png)

比特币交易信息中只有付款人的公钥，没有收款人的公钥

**Comment by yeasy** [comment]
Right, to be accurate, there is the hash of the public key from the receiver.

https://en.bitcoin.it/wiki/Transaction
