### ISSUE TITLE
纸质书的3.6节 中“5.公共网络服务”部分的描述不太严谨。

### ISSUE THREAD

**Issue by qurikuduo** [yeasy/blockchain_guide#67]
![_20171220095011](https://user-images.githubusercontent.com/4517807/34187500-a6101bb6-e56c-11e7-9eb4-04dc1144d114.jpg)
个人意见，仅供参考：

1. “例如域名服务（DNS）”
最好改为“域名系统（Domain Name System，缩写：DNS）”
2. “没有DNS，现在的各种网站将无法访问。”
这句话不够严谨，建议最好改成“没有DNS，现在的各种网站将无法使用域名访问。”

**Comment by yeasy** [comment]
@qurikuduo thanks for the report, would u like to add the suggest at https://github.com/yeasy/blockchain_guide/wiki/%E3%80%8A%E5%8C%BA%E5%9D%97%E9%93%BE%E5%8E%9F%E7%90%86%E3%80%81%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%BA%94%E7%94%A8%E3%80%8B%E5%8B%98%E8%AF%AF%E8%A1%A8?

Thanks!

**Comment by qurikuduo** [comment]
got it
