### ISSUE TITLE
关于Merkle 树的零知识证明（zero-knowledge proof）。

### ISSUE THREAD

**Issue by tidus5** [yeasy/blockchain_guide#73]
零知识证明：例如如何证明某个数据（D0……D3）中包括给定内容 D0，很简单，构造一个默克尔树，公布 N0，N1，N4，Root，D0 拥有者可以很容易检测 D0 存在，但不知道其它内容。

为什么拥有者不直接公布 N0   ，那么，D0拥有者就可以信任对方拥有内容 D0。
因为D0拥有者不知道其他数据，N1, N4, Root 给他没用， 也无法验证正确性啊。

---
About zero-knowledge proof in Merkle tree.
Why not just use N0  as the proof of owning D0?

**Comment by yeasy** [comment]
证明拥有D0，但是不能暴露额外的信息，包括D0的内容。

**Comment by tidus5** [comment]
拥有者公布D0 的 Hash值  N0 ，就可以证明拥有D0啊。构造Merkle 树的作用是什么呢？ 可否解答一下
@yeasy

**Comment by yeasy** [comment]
D0 的 Hash 值也是相关的信息。

**Comment by Barbery** [comment]
这个问题我也有点不解。。。看来下大家的回答，还是不解

**Comment by yeasy** [comment]
其实在实践领域里，往往是：针对某个特定的问题。双方先商量共识出对这个问题的一个变种问题——若某一方能快速解决这个变种，说明应该很大概率知道怎么解决原问题（否则很难快速解决变种问题），但是从变种问题的答案本身，无法推出如何解决原问题（零知识）。

**Comment by YaoYufeng** [comment]
关于文章中的
仍以上图为例，如何向他人证明拥有某个数据 D0 而不暴露其它信息。挑战者提供随机数据 D1，D2 和 D3，或由证明人生成（需要加入特定信息避免被人复用证明过程）。
证明人构造如图所示的默克尔树，公布 N1，N5，Root。验证者自行计算 Root 值，验证是否跟提供值一致，即可很容易检测 D0 存在。整个过程中验证者无法获知与 D0 相关的额外信息。
请问作者有证明过程吗？我思考了很久，希望能够解读～

**Comment by shingsheep** [comment]
您好：    您的来信已收悉，我会尽快回复。谢谢。

**Comment by SirKong** [comment]
谢谢您的邮件，我已收到，我会尽快给您回复。
