### ISSUE TITLE
请问orderer集群如何配置

### ISSUE THREAD

**Issue by zhang-gq** [yeasy/blockchain_guide#74]
您好！
我在看您的《区块链：原理、设计与应用》，10.4.1章节也提到了orderer集群。
但是具体怎么配置呢？
您的例子都是指定一个orderer，请问如何指定多个orderer。
我看有的人说就正常建立多个orderer节点，orderer都是用同一个kafka，
peer channel create -o 任意指定一个orderer就可以，后续kafka会分配给某个orderer处理。
也有人说通过HAProxy反向代理到某个orderer。
您能指点一下吗，不胜感谢。

**Comment by yeasy** [comment]
多个orderer之间并无关联，因此，单独启动多个orderer节点即可。
客户端可以根据自己需求选择访问的orderer节点。

**Comment by wbwangk** [comment]
自己看fabric文档，好好学习一下就知道了：https://hyperledgercn.github.io/hyperledgerDocs/
