### ISSUE TITLE
拜占庭问题：为什么会有f个可信节点离线呀？

### ISSUE THREAD

**Issue by friends110110** [yeasy/blockchain_guide#86]
请问为什么  并且 $$g$$ 个忠诚者中有 $$f$$ 个离线时 ？为什么是f个？
当 $$f$$ 个叛变者都给出一个恶意的提案，并且 $$g$$ 个忠诚者中有 $$f$$ 个离线时，剩下的 $$g - f$$ 个忠诚者此时无法分别是否混入了叛变者，仍然要确保取多数能得到正确结果，因此，$$g - f > f$$，即 $$g > 2f$$，所以系统整体规模要大于 $$3f$$。

**Comment by yeasy** [comment]
As bft allows f's failures. Offline is also one kind of failure.

Btw, pls provide the context or link when ask questions.

Thanks!
