### ISSUE TITLE
English Version Please

### ISSUE THREAD

**Issue by gungunfebrianza** [yeasy/blockchain_guide#88]
I try convert the language to english but seems i loss many nuance and information. So it's hard to understand. could you make the english version? so all people in the whole world can read this guide.

thanks
Gun Gun Febrianza

**Comment by yeasy** [comment]
Hey, glad that you enjoy the book.

We've started an [English](https://github.com/yeasy/blockchain_guide/tree/i18n_en) branch already.

And welcome anyone to help improve, too!

Thanks!
