### ISSUE TITLE
5.1 2018 version of this book , page 133, 编译安装fabric-ca组件， at the end of command a dot was missed 

### ISSUE THREAD

**Issue by meilier** [yeasy/blockchain_guide#95]

**Comment by yeasy** [comment]
@meilier 好眼力！
欢迎到https://github.com/yeasy/blockchain_guide/wiki/%E3%80%8A%E5%8C%BA%E5%9D%97%E9%93%BE%E5%8E%9F%E7%90%86%E3%80%81%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%BA%94%E7%94%A8%E3%80%8B%E5%8B%98%E8%AF%AF%E8%A1%A8，添加一个记录。
谢谢！
